Tier1 dodrio extension
hpcleuven/VSC-XDMoD pull request #42
Opened 2023-06-20 08:01 UTC by itkovian

2023-06-20 08:05 UTC, wpoely86 approved these changes

2023-06-20 08:05 UTC, wpoely86 commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2013-05015"
```suggestion
    "start_date": "2013-05-15"
```

2023-06-20 08:05 UTC, wpoely86 commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2008-11-01"
`end_date`?

2023-06-28 07:37 UTC, WouterVanAssche requested changes
If end dates are  known, also add end dates where possible.

2023-06-28 07:37 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2020-10-27"
ppn * nodes = processors
40 * 48 = 1920

2023-09-21 07:20 UTC, merged