Epauwels patch 1
hpcleuven/VSC-XDMoD pull request #45
Opened 2023-09-14 07:59 UTC by epauwels

Added end dates for all Tier1/Tier2 clusters at Ghent that were decommissioned

2023-09-14 08:19 UTC, wpoely86 commented on resource_files/UGent/resource_specs.json
> +    "processors": 960,
```suggestion
    "processors": 1920,
```

2023-09-14 08:20 UTC, wpoely86 commented on resource_files/UGent/resource_specs.json
> +    "processors": 960,
```suggestion
    "processors": 1920,
```

2023-09-18 12:57 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "ppn": 36
missing comma at end of line

2023-09-18 13:02 UTC, WouterVanAssche requested changes
There are a couple lines with missing commas. I've marked them with comments.
The rest seems Ok.

2023-09-18 13:02 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-06-10"
missing comma at end of line

2023-09-18 13:02 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-09-05"
missing comma at end of line

2023-09-18 13:02 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2012-06-15"
missing comma at end of line

2023-09-18 13:02 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-02-14"
missing comma at end of line

2023-09-18 13:02 UTC, WouterVanAssche commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2020-12-09"
missing comma at end of line

2023-09-18 13:16 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2020-12-09"
All commas should now be in place

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2013-05-15"
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2015-01-13"
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "ppn": 36
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2020-02-13"
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2008-11-01"
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2009-12-01"
fixed

2023-09-19 10:03 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2010-01-01"
fixed

2023-09-19 10:04 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-06-10"
fixed

2023-09-19 10:04 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-09-05"
fixed

2023-09-19 10:04 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2012-06-15"
fixed

2023-09-19 10:04 UTC, epauwels commented on resource_files/UGent/resource_specs.json
> +    "start_date": "2011-02-14"
fixed

2023-09-21 07:19 UTC, WouterVanAssche approved these changes

2023-09-21 07:20 UTC, merged